namespace :generate do
  desc 'Generate a timestamped, empty Sequel migration.'
  task :migration, :name do |_, args|
    if args[:name].nil? || args[:namespace].nil?
      puts 'You must specify a migration name (e.g. rake generate:migration[create_events,director])!'
      exit false
    end
 
    content = "Sequel.migration do\n  up do\n    \n  end\n\n  down do\n    \n  end\nend\n"
    namespace = args[:namespace]
    timestamp = Time.now.strftime('%Y%m%d%H%M%S')
    filename = File.join(File.dirname(__FILE__), 'db', 'migrations', namespace, "#{timestamp}_#{args[:name]}.rb")
 
    File.open(filename, 'w') do |f|
      f.puts content
    end
 
    puts "Created the migration #{filename}"
  end
end
